env:
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'import/no-extraneous-dependencies': 0,
  'no-underscore-dangle': 0,
  'import/no-duplicates': 0,
  "import/extensions": 0,
  'no-console': 0,
}